base_url = "https://vitadatreno.it"
title = "Vitadatreno"
theme = "zhuia"
default_language = "it"

# Variabili extra richieste dal tema
[extra]
author = "M. Farina"
show_author = true
show_categories = true
show_tags = true
og_image = "img/cover.png"
read_post_prompt = "Continue Reading â†’"
color_mode = "light"


# sidebar
sidebar.active = true
sidebar.author_bio = "Autore del blog"
sidebar.author_avatar = "img/profile.jpg"

# menu principale
main_menu = [
    { name = "Home", url = "/" },
    { name = "Blog", url = "/blog/" },
    { name = "About", url = "/about/" }
]





# Paginazione globale (opzionale)
paginate_by = 5
