base_url = "https://tuosito.github.io"
title = "Il mio blog"
default_language = "it"
theme = "papaya"
generate_feeds = true

[extra]
color_mode = "light"

[extra.cdn]
font_awesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"

menu_items = [
  { name = "Home", url = "/" },
  { name = "Blog", url = "/blog" }
]

# Traduzioni minime richieste da Papaya
[translations.it]
blog = "Blog"
